# Generated by Django 5.2.11 on 2026-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, default='', verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Podre'), (1, 'Ruim'), (2, 'Meh'), (3, 'Bom'), (4, 'Muito Bom'), (5, 'Obra de Arte')], verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
    ]
